# Generated by Django 4.2.7 on 2025-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_cost_limit',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Maximum allowed API spending (USD) - default $0.50 for free users', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_limit_reached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user hit their API limit', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_api_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Total API costs incurred (USD) - admin view only', max_digits=10),
        ),
    ]
