# Generated by Django 4.2.7 on 2025-10-14 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_discountcode_payment_subscription_referralreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_per_doc_reward_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage of Pay-Per-Doc sale to give as reward (e.g., 20.00 = 20%)', max_digits=5)),
                ('unlimited_reward_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage of Unlimited sale to give as reward (e.g., 20.00 = 20%)', max_digits=5)),
                ('use_percentage_rewards', models.BooleanField(default=True, help_text='If unchecked, uses flat rate rewards below instead of percentages')),
                ('flat_pay_per_doc_reward', models.DecimalField(decimal_places=2, default=25.0, help_text='Flat dollar amount for Pay-Per-Doc referrals (if not using percentage)', max_digits=6)),
                ('flat_unlimited_reward', models.DecimalField(decimal_places=2, default=25.0, help_text='Flat dollar amount for Unlimited referrals (if not using percentage)', max_digits=6)),
                ('default_referral_discount_percentage', models.DecimalField(decimal_places=2, default=25.0, help_text='Default discount % for new referral codes (e.g., 25% off)', max_digits=5)),
                ('is_promotional_period', models.BooleanField(default=False, help_text='Enable promotional rewards (Black Friday, etc.)')),
                ('promo_pay_per_doc_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Promotional reward % for Pay-Per-Doc', max_digits=5)),
                ('promo_unlimited_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Promotional reward % for Unlimited', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Setting',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
    ]
