# Generated by Django 4.2.7 on 2025-10-15 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_referralsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referral_cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Referral earnings available for cash withdrawal', max_digits=10),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('api_credit', 'Convert to API Credit'), ('other', 'Other')], default='paypal', max_length=20)),
                ('payment_email', models.EmailField(blank=True, help_text='PayPal/Venmo email', max_length=254)),
                ('payment_phone', models.CharField(blank=True, help_text='Zelle/phone number', max_length=20)),
                ('payment_address', models.TextField(blank=True, help_text='Mailing address for checks')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='PayPal transaction ID, check number, etc.', max_length=255)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
