# Generated by Django 4.2.7 on 2025-10-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscription_referral_cash_balance_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referred_by_code',
            field=models.CharField(blank=True, help_text='Referral code used during signup', max_length=50, null=True),
        ),
    ]
