# Generated by Django 4.2.7 on 2025-10-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userprofile_referred_by_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable promotional pricing across the site')),
                ('regular_price', models.DecimalField(decimal_places=2, default=197.0, help_text='Regular price for document ($197)', max_digits=6)),
                ('promo_price', models.DecimalField(decimal_places=2, default=129.0, help_text='Promotional price for document ($129)', max_digits=6)),
                ('promo_badge_text', models.CharField(default='LAUNCH SPECIAL', help_text="Badge text shown on pricing (e.g., 'LAUNCH SPECIAL', 'LIMITED TIME', 'BLACK FRIDAY')", max_length=50)),
                ('promo_headline', models.CharField(default='Launch Discount - Save $68!', help_text='Main headline for promotion', max_length=200)),
                ('promo_description', models.TextField(default='Get our complete Section 1983 document generator at our special launch price. Limited time offer for early adopters.', help_text='Description text for promotion')),
                ('promo_urgency_text', models.CharField(blank=True, default='', help_text="Optional urgency text (e.g., 'Offer ends December 31st', 'Only 50 spots left')", max_length=200)),
                ('show_countdown', models.BooleanField(default=False, help_text='Show countdown timer (requires end date)')),
                ('promo_end_date', models.DateTimeField(blank=True, help_text='When promotion ends (optional - for countdown)', null=True)),
                ('stripe_promo_price_id', models.CharField(blank=True, help_text='Stripe Price ID for promotional price (e.g., price_xxxxx)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotional Pricing Setting',
                'verbose_name_plural': 'Promotional Pricing Settings',
            },
        ),
    ]
