# Generated by Django 4.2.7 on 2025-10-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_promosettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='api_credit_balance',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_credit_refill',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('standard', 'Standard Plan - Document Purchase'), ('addon_bundle', 'Add-on Bundle - AI + Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic (Free Trial)'), ('standard', 'Standard')], default='basic', max_length=20),
        ),
    ]
