# Generated by Django 4.2.7 on 2025-10-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_video_extraction_limits'),
        ('accounts', '0008_remove_subscription_api_credit_balance_and_more'),
    ]

    operations = [
    ]
