# Generated by Django 4.2.7 on 2025-09-20 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawsuitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Brief description of the civil rights violation')),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=300)),
                ('defendants', models.TextField(blank=True, help_text='Names and positions of defendants')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video showing the violation')),
                ('additional_evidence', models.TextField(blank=True, help_text='Description of other evidence')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('filed', 'Filed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuit_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'Introduction'), ('jurisdiction', 'Jurisdiction and Venue'), ('parties', 'Parties'), ('facts', 'Statement of Facts'), ('claims', 'Claims for Relief'), ('prayer', 'Prayer for Relief'), ('jury_demand', 'Jury Trial Demand')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.lawsuitdocument')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('document', 'section_type')},
            },
        ),
    ]
