# Generated by Django 4.2.7 on 2025-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsuitdocument',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_1',
            field=models.URLField(blank=True, help_text='Primary video evidence'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_2',
            field=models.URLField(blank=True, help_text='Additional video evidence'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_3',
            field=models.URLField(blank=True, help_text='Additional video evidence'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_4',
            field=models.URLField(blank=True, help_text='Additional video evidence'),
        ),
    ]
