# Generated by Django 4.2.7 on 2025-09-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_lawsuitdocument_youtube_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('threatened_arrest_public', 'Threatened Arrest in Public Area'), ('interference_recording', 'Interference with Recording'), ('forced_to_leave_public', 'Forced to Leave Public Area')], max_length=50)),
                ('location_type', models.CharField(choices=[('traditional_public_forum', 'Traditional Public Forum'), ('designated_public_forum', 'Designated Public Forum'), ('limited_public_forum', 'Limited Public Forum')], max_length=50)),
                ('section_type', models.CharField(max_length=20)),
                ('template_text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('violation_type', 'location_type', 'section_type')},
            },
        ),
    ]
