# Generated by Django 4.2.7 on 2025-09-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_legaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuitdocument',
            name='include_videos_in_document',
            field=models.BooleanField(default=False, help_text='Include video URLs as formal exhibits in the legal document'),
        ),
    ]
