# Generated by Django 4.2.7 on 2025-09-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_lawsuitdocument_include_videos_in_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuitdocument',
            name='district_lookup_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('low', 'Low Confidence'), ('manual', 'Manually Selected')], max_length=20),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='incident_city',
            field=models.CharField(blank=True, help_text='City where incident occurred', max_length=100),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='incident_state',
            field=models.CharField(blank=True, help_text='State where incident occurred', max_length=50),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='incident_street_address',
            field=models.CharField(blank=True, help_text='Street address where incident occurred', max_length=200),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='incident_zip_code',
            field=models.CharField(blank=True, help_text='ZIP code where incident occurred', max_length=20),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='suggested_federal_district',
            field=models.TextField(blank=True, help_text='Auto-suggested federal district court'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='user_confirmed_district',
            field=models.TextField(blank=True, help_text='User-confirmed federal district court'),
        ),
        migrations.AlterField(
            model_name='lawsuitdocument',
            name='incident_location',
            field=models.CharField(blank=True, help_text='Full address or description of where incident occurred', max_length=300),
        ),
        migrations.AlterField(
            model_name='legaltemplate',
            name='violation_type',
            field=models.CharField(choices=[('threatened_arrest_public', 'Threatened Arrest in Public Area'), ('interference_recording', 'Interference with Recording'), ('forced_to_leave_public', 'Forced to Leave Public Area'), ('retaliation_protected_speech', 'Retaliation for Protected Speech')], max_length=50),
        ),
    ]
