# Generated by Django 4.2.7 on 2025-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_lawsuitdocument_district_lookup_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuitdocument',
            name='use_manual_court',
            field=models.BooleanField(default=False, help_text='Whether user manually entered court district'),
        ),
    ]
