# Generated by Django 4.2.7 on 2025-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_lawsuitdocument_use_manual_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_1_end_time',
            field=models.CharField(blank=True, help_text='End timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_1_start_time',
            field=models.CharField(blank=True, help_text='Start timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_1_transcript',
            field=models.TextField(blank=True, help_text='Extracted transcript snippet'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_2_end_time',
            field=models.CharField(blank=True, help_text='End timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_2_start_time',
            field=models.CharField(blank=True, help_text='Start timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_2_transcript',
            field=models.TextField(blank=True, help_text='Extracted transcript snippet'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_3_end_time',
            field=models.CharField(blank=True, help_text='End timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_3_start_time',
            field=models.CharField(blank=True, help_text='Start timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_3_transcript',
            field=models.TextField(blank=True, help_text='Extracted transcript snippet'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_4_end_time',
            field=models.CharField(blank=True, help_text='End timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_4_start_time',
            field=models.CharField(blank=True, help_text='Start timestamp (MM:SS)', max_length=10),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='youtube_url_4_transcript',
            field=models.TextField(blank=True, help_text='Extracted transcript snippet'),
        ),
    ]
