# Generated by Django 4.2.7 on 2025-10-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_lawsuitdocument_youtube_url_1_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Full YouTube URL')),
                ('video_title', models.CharField(blank=True, help_text='Auto-fetched from YouTube', max_length=300)),
                ('start_time', models.CharField(help_text='Start time (MM:SS or HH:MM:SS)', max_length=10)),
                ('end_time', models.CharField(help_text='End time (MM:SS or HH:MM:SS)', max_length=10)),
                ('start_seconds', models.IntegerField(help_text='Start time in seconds for sorting')),
                ('end_seconds', models.IntegerField(help_text='End time in seconds')),
                ('raw_transcript', models.TextField(blank=True, help_text='Original AI-generated transcript (preserved)')),
                ('edited_transcript', models.TextField(blank=True, help_text='User-edited transcript with speaker attribution')),
                ('manually_entered', models.BooleanField(default=False, help_text='True if transcript was manually entered')),
                ('violation_tags', models.CharField(blank=True, help_text='Comma-separated violation types: first_amendment,fourth_amendment,etc', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='User notes about this segment')),
                ('is_reviewed', models.BooleanField(default=False, help_text='User has reviewed and approved')),
                ('include_in_complaint', models.BooleanField(default=False, help_text='Include in final document')),
                ('extraction_cost', models.DecimalField(blank=True, decimal_places=4, help_text='API cost in USD', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_evidence', to='documents.lawsuitdocument')),
            ],
            options={
                'verbose_name': 'Video Evidence Segment',
                'verbose_name_plural': 'Video Evidence Segments',
                'ordering': ['youtube_url', 'start_seconds'],
            },
        ),
    ]
