# Generated by Django 4.2.7 on 2025-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_videoevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsection',
            name='section_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('jurisdiction', 'Jurisdiction and Venue'), ('parties', 'Parties'), ('facts', 'Statement of Facts'), ('claims', 'Claims for Relief'), ('prayer', 'Prayer for Relief'), ('jury_demand', 'Jury Trial Demand'), ('exhibits', 'List of Exhibits')], max_length=20),
        ),
    ]
