# Generated by Django 4.2.7 on 2025-10-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentsection_ai_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=200)),
                ('role', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('witness', 'Witness'), ('other', 'Other')], help_text='Role in the case', max_length=20)),
                ('title', models.CharField(blank=True, help_text="Job title or position (e.g., 'Officer', 'Detective')", max_length=200)),
                ('badge_number', models.CharField(blank=True, help_text='Badge number for law enforcement', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this person')),
                ('color_code', models.CharField(default='#6c757d', help_text='Color for highlighting (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='ai_generations_purchased',
            field=models.IntegerField(default=2, help_text='Total AI generations purchased for this document (Basic: 2, Standard: 10 + add-ons)'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='ai_generations_used',
            field=models.IntegerField(default=0, help_text='Number of AI generations used so far'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='extraction_minutes_purchased',
            field=models.IntegerField(default=5, help_text='Total video extraction minutes purchased (Basic: 5, Standard: 30 + add-ons)'),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='extraction_minutes_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Video extraction minutes used so far', max_digits=6),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='purchased_at',
            field=models.DateTimeField(blank=True, help_text='When the Standard plan was purchased for this document', null=True),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lawsuitdocument',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe payment ID - indicates document was purchased', max_length=255),
        ),
        migrations.AddField(
            model_name='videoevidence',
            name='source_description',
            field=models.TextField(blank=True, help_text='Additional description of video source (optional)'),
        ),
        migrations.AddField(
            model_name='videoevidence',
            name='source_type',
            field=models.CharField(choices=[('body_camera', 'Body Camera Footage'), ('plaintiff_recorded', 'Plaintiff-Recorded Video'), ('surveillance', 'Surveillance Camera'), ('dashboard_camera', 'Dashboard Camera'), ('witness_recorded', 'Witness-Recorded Video'), ('other', 'Other')], default='body_camera', help_text='Type/origin of video footage', max_length=50),
        ),
        migrations.CreateModel(
            name='TranscriptQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual quoted text from the transcript')),
                ('start_position', models.IntegerField(help_text='Character start position in edited_transcript')),
                ('end_position', models.IntegerField(help_text='Character end position in edited_transcript')),
                ('approximate_timestamp', models.CharField(blank=True, help_text='Approximate timestamp within segment (MM:SS)', max_length=20)),
                ('significance', models.CharField(blank=True, help_text="Why this quote is significant (e.g., 'Unlawful demand for ID')", max_length=300)),
                ('violation_tags', models.CharField(blank=True, help_text='Comma-separated violation types: fourth_amendment,first_amendment,excessive_force,etc', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Additional context or notes about this quote')),
                ('sort_order', models.IntegerField(default=0, help_text='Manual sort order within segment')),
                ('include_in_document', models.BooleanField(default=True, help_text='Include this quote in AI-generated document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(help_text='Who said this quote', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='documents.person')),
                ('video_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='documents.videoevidence')),
            ],
            options={
                'verbose_name': 'Transcript Quote',
                'verbose_name_plural': 'Transcript Quotes',
                'ordering': ['video_evidence', 'sort_order', 'start_position'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='documents.lawsuitdocument'),
        ),
        migrations.CreateModel(
            name='DocumentAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('bundle', 'AI + Video Bundle')], default='bundle', help_text='Type of add-on purchased', max_length=20)),
                ('ai_generations_added', models.IntegerField(default=20, help_text='AI generations added by this purchase')),
                ('extraction_minutes_added', models.IntegerField(default=15, help_text='Video extraction minutes added by this purchase')),
                ('amount', models.DecimalField(decimal_places=2, default=29.0, help_text='Amount paid for this add-on', max_digits=6)),
                ('stripe_payment_intent_id', models.CharField(max_length=255)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_purchases', to='documents.lawsuitdocument')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('document', 'name', 'role')},
        ),
    ]
