# Generated by Django 4.2.7 on 2025-10-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_person_transcriptquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoevidence',
            name='source_description',
            field=models.TextField(blank=True, help_text='Additional description of video source (optional)'),
        ),
        migrations.AddField(
            model_name='videoevidence',
            name='source_type',
            field=models.CharField(choices=[('body_camera', 'Body Camera Footage'), ('plaintiff_recorded', 'Plaintiff-Recorded Video'), ('surveillance', 'Surveillance Camera'), ('dashboard_camera', 'Dashboard Camera'), ('witness_recorded', 'Witness-Recorded Video'), ('other', 'Other')], default='body_camera', help_text='Type/origin of video footage', max_length=50),
        ),
    ]
