# Generated by Django 4.2.7 on 2025-10-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_person_lawsuitdocument_ai_generations_purchased_and_more'),
        ('documents', '0013_videoevidence_source_description_and_more'),
    ]

    operations = [
    ]
